---
title: Summary-2018
author: Micah and Aaron
date: February 11, 2018
output:
  html_document:
    fig_height: 50
    fig_width: 50
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r libraries, warning=FALSE, message=FALSE, echo=FALSE, results='hide'}
require("RPostgreSQL")
require("plotly")

pw <- {""}
drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv, dbname = "gnascar",
                 host = "localhost", port = 5432,
                 user = "mgaither", password = pw)

# query the data from postgreSQL 
season2017 <- dbGetQuery(con, "SELECT * from season_2017")

# query the data from postgreSQL 
standings2017 <- dbGetQuery(con, "SELECT * from standings_2017")

# 2017 Roster Standings
xform <- list(categoryorder = "array",
              categoryarray = c("LazyDogDad", 
                                "GatorDad", 
                                "SlobberRacing",
                                "GatorMom",
                                "RidgeRacing",
                                "LazyDogMom",
                                "JulianGangsta",
                                "Chug",
                                "Field"))


a <- list(
  x = seasonstandings2017$Rank,
  y = seasonstandings2017$AvSt,
  text = "WINNER"
  xref = "x",
  yref = "y",
  showarrow = TRUE,
  arrowhead = 7,
  ax = 1,
  ay = 2000
)

p4 <- plot_ly(standings2017, x = ~Owner, y = ~Points, type = 'bar', text=~Driver, 
              color = ~Owner, colors = "Pastel1", 
              textposition = 'auto', marker = list(line = list(color = 'gray36', width = 1))) %>% 
    layout(yaxis = list(title = 'Points'), xaxis = list(title = ""), barmode = 'stack', plot_bgcolor = 'rgba(245, 246, 249, 1)') %>% layout(xaxis = xform)

seasonstandings2017 <- merge(season2017, standings2017,by=c("Driver"))

p3 <- plot_ly(seasonstandings2017, x = ~Rank, y = ~AvSt, type = 'scatter', mode = 'markers',
  marker = list(line = list(color = 'rgba(152, 0, 0, .8)', width = 2)),
  hoverinfo = 'text',
  text = ~paste('Driver: ', Driver, '</br>',
                '</br>Owner: ', Owner,
                '</br>Rank: ', Rank,
                '</br>Points: ', Points.x,
                '</br>Wins: ', Win,
                '</br>Poles: ', Poles,
                '</br>DNF: ', DNF,
                '</br>Average Start: ', AvSt, 
                '</br>Average Finish:', AvFn),
  color = ~Owner, colors = "Paired", size = ~DNF) %>%
  layout(title = "",
         xaxis = list(title = "Ranking", zeroline = FALSE),
         yaxis = list (title = "Average Starting Position", zeroline = FALSE),
         plot_bgcolor = 'rgba(245, 246, 249, 1)') %>%
  layout(annotations = a)

```

# GNASCAR 2017

## Driver Ranking v. Average Starting Position
```{r, results='asis', echo=FALSE, warning=FALSE}
htmltools::tagList(list(p3))
```

### Cumulative Driver Points by Team
```{r, results='asis', echo=FALSE, warning=FALSE}
htmltools::tagList(list(p4))
```

```{r}

```
  
# Appendix   

## Driver Statistics
```{r, results = 'asis', echo=FALSE}
knitr::kable(standings2017[order(standings2017$Rank),])
```


